---
- name: (Sudo) Create sudoers.d directory
  tags:
    - sudo
    - configuration
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: (Sudo) Set includedir in sudoers
  tags:
    - sudo
    - configuration
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: (Sudo) Enable sudoers in 'sudo_sudoers_enabled'
  tags:
    - sudo
    - configuration
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: item.name in sudo_sudoers_enable
  with_items:
    - "{{ sudoers_d }}"

- name: (Sudo) Remove sudoers if not in 'sudo_sudoers_enabled'
  tags:
    - sudo
    - configuration
  file:
    path: "/etc/sudoers.d/{{ item.name }}"
    state: absent
  when: not item.name in sudo_sudoers_enable
  with_items:
    - "{{ sudoers_d }}"
