---
- name: SUDO | Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: SUDO | Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: SUDO | Enable sudoers in 'sudo_sudoers_enabled'
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: item.name in sudo_sudoers_enabled
  with_items:
    - "{{ sudoers_d }}"

- name: SUDO | Remove sudoers if not in 'sudo_sudoers_enabled'
  file:
    path: "/etc/sudoers.d/{{ item.name }}"
    state: absent
  when: not item.name in sudo_sudoers_enabled
  with_items:
    - "{{ sudoers_d }}"
